version: '3.4'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.0
    container_name: zookeeper
    env_file:
      - ./conf/zookeeper.env
    ports:
      - 2181:2181
    command: sh -c "echo 'admin.enableServer=false' >> /etc/confluent/docker/zookeeper.properties.template && /etc/confluent/docker/run"

  kafka:
    container_name: kafka
    build:
      context: .
      dockerfile: ./dev/kafka/Dockerfile
    env_file:
      - ./conf/kafka.env
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
      - 29093:29093
      - 9092:9092
      - 9093:9093
