
name: 🕵️ Codecov

on:
  push:
  pull_request:
    types: [ "opened", "synchronize", "reopened" ]

jobs:
  codecov:
    name: Codecov
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: codecov/codecov-action@v1
      with:
        name: codecov-umbrella # optional
        fail_ci_if_error: false # optional (default = false)
        verbose: true # optional (default = false)
